readHSPFts <- function(RF)
 # read timeseries of HRUs integrations generated by topHSPF
 #                    saveBinfl = 0,
 #                    savehdf5  = FALSE,
 #                    rmScratch = TRUE,
{

  m <- RF$m
  dsn  <- RF$path$outsfld                                   # model output folder: time series
  seqT <- seq(trunc(RF$timenow,'hour'), RF$timenex, by=RF$dto)            # model IO times
  if (max(seqT) < RF$timenex)
    seqT <- c(seqT,max(seqT)+RF$dto)                        # cover next interruption point (timenex)
  nto <- length(seqT)
  simseqT <- seq(min(seqT),max(seqT),by=RF$dti)[-1]         # model output [initial time not included]
  nti <- length(simseqT)
  
  innhrus  <- ifelse(RF$nhrus > 1, RF$nhrus+1, 1)           # number of forecast timeseries (RHUs plus one lumped output)

  # binary timeseries generated by topHSPF
  vnames <- c("rain","petinp","ceps","surs","ifws","uzs","lzs","agws",
              "supy","suro","ifwo","agwo","pero","igwi",
              "cepe","uzet","lzet","agwet","baset","taet",
              "ifwi","uzi","infil","perc","lzi","agwi",
              "suri","rempet","gwvs","watin","watdif",
              "pers")

  Ets <- vector('list', length(vnames))
  for (iv in 1:length(Ets)) {
    for (iu in 1:innhrus) {
      Ets[[iv]][[iu]] <- list()
      Ets[[iv]][[iu]]$time  <- simseqT
      Ets[[iv]][[iu]]$sim   <- matrix(NA,nti,m)
      Ets[[iv]][[iu]]$units <- 'mm'
    }
  }
  names(Ets) <- vnames

  # get forecast data
  imStrs <- formatC(1:m,width=5,flag="0",format="d")
  #browser()
  for (iv in 1:length(Ets)) {
    fname <- paste(vnames[iv],"_hru_bin.ts",sep="")
    for (im in 1:m) {
      tmp <- matrix(readBin(file.path(dsn,imStrs[im],fname),
                                  what="double", n=nti*innhrus),
                                  nrow=nti, ncol=innhrus, byrow=TRUE) # topHSPF transposes TS output to prevent time-derived imbalances here
      for (iu in 1:innhrus) {
        Ets[[iv]][[iu]]$sim[,im] <- tmp[,iu]
      } # end for iu
    } # end for im
  } # end for iv
  
  #save(modres, file=paste(outfld.ts,"/spsums_",runpidfmt,".Rdata",sep=""))       # re-export as an R structure
  #if(rmScratch){
  #  file.remove(c(fgeometap, fmaskp, fhrusp, frainp, fpetinpp,
  #               fparsp, modelfilep, mainfilep,
  #               file.path(outfld.ts.pid,tmptsf)
  #              ))
  #  file.remove(outfldp.pid)
  #  file.remove(outfld.ts.pid)
  #}
  return(Ets)
}
