GFORTRAN module version '0' created from /home/pt902904/docs/hydrology/tophspf/src/ModuleHspfPwater.F90 on Mon Mar  7 08:12:47 2016
MD5:e077676504a7c55aa1a1d26e884a7932 -- If you edit this, you'll get what you deserve.

(() () () () () () () () () () () ()
() () () () () () () () () () () () () () ())

()

()

()

()

(2 'hspf_pwater' 'modulehspfpwater' 'hspf_pwater' 1 ((PROCEDURE
UNKNOWN-INTENT MODULE-PROC DECL UNKNOWN SUBROUTINE) (UNKNOWN 0 0 0
UNKNOWN ()) 3 0 (4) () 0 () () () 0 0)
5 'surs' 'modulehspfpwater' 'surs' 1 ((VARIABLE UNKNOWN-INTENT
UNKNOWN-PROC UNKNOWN UNKNOWN ALLOCATABLE DIMENSION) (REAL 8 0 0 REAL ())
0 0 () (2 DEFERRED () () () ()) 0 () () () 0 0)
4 'modelfilep' '' 'modelfilep' 3 ((VARIABLE IN UNKNOWN-PROC UNKNOWN
UNKNOWN DUMMY) (CHARACTER 1 0 0 CHARACTER (())) 0 0 () () 0 () () () 0 0)
)

('hspf_pwater' 0 2 'surs' 0 5)
